### PR TITLE
Returns map in pixel space

### PR DESCRIPTION
**Pull request by louisl3grand**
Allows to define maps in harmonic space but to output them in pixel space.

### CODE REVIEW

**Comment by Sebastian-Belkner** [comment]
Why don't you just inherit from class cmb_maps, returning pixel space maps already exist there

**Review by carronj — COMMENTED** [review]
My only worry is that the change in hashdict will break my current recs... :) Otherwise fine

**Comment by louisl3grand** [comment]
The idea is to have the Cls noise as inputs instead of the Gaussian noise defined by noise levels and beam. 
Also the doc of the functions cmb_maps_harmonicspace.get_sim_tmap and  cmb_maps_harmonicspace.get_sim_pmap say they return healpy maps but it returns alm's

**Comment by louisl3grand** [comment]
Yes hashdict will be annoying, in that case maybe we can do another class.

**Comment by carronj** [comment]
For me it would be fine to leave out nside of the hashdict, since this does not actually change the alm array so is non-critical

**Pull request merged**
